In [1]:
# list, tuple, set, dic, numpy, pandas
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
v1 = np.array([1,2,3,4])
print(v1)

[1 2 3 4]


In [3]:
v1 = np.arange(5)
print(f'v1의 값은 {v1}')

v1의 값은 [0 1 2 3 4]


In [4]:
v2 = np.arange(1, 10, 2,  dtype=int)
print(f'v2의 값은 {v2}')

v2의 값은 [1 3 5 7 9]


In [5]:
v3 = np.arange(3.5, 10.5, 2,  dtype=float)
print(f'v3의 값은 {v2}')

v3의 값은 [1 3 5 7 9]


In [6]:
v4 = np.arange(1, 10, 2)**2
print(f'v4의 제곱 값은 {v4}')

v4의 제곱 값은 [ 1  9 25 49 81]


In [7]:
v4 = np.arange(1, 10, 2)**3
print(f'v4의 3제곱 값은 {v4}')

v4의 3제곱 값은 [  1  27 125 343 729]


In [8]:
v5 = np.arange(12)
print(v5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
v6 = v5.reshape(2, 6)
print(v6)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [10]:
v6 = v5.reshape(2, 6, order='F')
print(v6)

[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]


In [11]:
v7 = np.arange(1, 5).reshape(2, 2)
print(v7)
print(np.add(v7, v7))
print(np.subtract(v7, v7))
print(np.multiply(v7, v7))
print(np.dot(v7, v7))

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [12]:
a = Series([1, 3, 5, 7])
print(a)

0    1
1    3
2    5
3    7
dtype: int64


In [13]:
print(a.values)

[1 3 5 7]


In [14]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)


In [15]:
a2 = Series([1,3,5,7,], index=['a','b','c','d'])
print(a2)

a    1
b    3
c    5
d    7
dtype: int64


In [16]:
df = pd.read_csv('./Data/EX_GrapeData.csv')
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [17]:
df = pd.read_excel("./Data/EX_GrapeData.xlsx")
df

continent  brand  size  period  price
0           2      2  10.7   47.65  144.0
1           2      3  14.0   63.13  215.0
2           2      2   9.0   58.76  105.0
3           1      1   8.0   34.88   69.0
4           2      2  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

[63 rows x 5 columns]

In [18]:
df.head()

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0

In [19]:
df.tail()

continent  brand  size  period  price
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

In [20]:
df['price']

0     144.0
1     215.0
2     105.0
3      69.0
4     134.0
      ...  
58     21.5
59      NaN
60      NaN
61      NaN
62      NaN
Name: price, Length: 63, dtype: float64

In [21]:
df[['price']]

price
0   144.0
1   215.0
2   105.0
3    69.0
4   134.0
..    ...
58   21.5
59    NaN
60    NaN
61    NaN
62    NaN

[63 rows x 1 columns]

In [22]:
df[df.columns[[0, 2, 4]]]

continent  size  price
0           2  10.7  144.0
1           2  14.0  215.0
2           2   9.0  105.0
3           1   8.0   69.0
4           2  10.0  134.0
..        ...   ...    ...
58          1   5.0   21.5
59          2  21.0    NaN
60          2   5.0    NaN
61          2  13.0    NaN
62          2  31.0    NaN

[63 rows x 3 columns]

In [23]:
df.loc[:, 'size':'price']

size  period  price
0   10.7   47.65  144.0
1   14.0   63.13  215.0
2    9.0   58.76  105.0
3    8.0   34.88   69.0
4   10.0   55.53  134.0
..   ...     ...    ...
58   5.0   16.66   21.5
59  21.0   43.00    NaN
60   5.0   12.00    NaN
61  13.0   20.00    NaN
62  31.0   19.00    NaN

[63 rows x 3 columns]

In [24]:
df.iloc[1:7, 0:2]

continent  brand
1          2      3
2          2      2
3          1      1
4          2      2
5          2      2
6          2      2

In [25]:
df_2 = df.copy()

In [26]:
df_2

continent  brand  size  period  price
0           2      2  10.7   47.65  144.0
1           2      3  14.0   63.13  215.0
2           2      2   9.0   58.76  105.0
3           1      1   8.0   34.88   69.0
4           2      2  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

[63 rows x 5 columns]

In [27]:
df_2.columns

Index(['continent', 'brand', 'size', 'period', 'price'], dtype='object')

In [28]:
df_3 = df[['size','period','price']].copy()

In [29]:
df_3

size  period  price
0   10.7   47.65  144.0
1   14.0   63.13  215.0
2    9.0   58.76  105.0
3    8.0   34.88   69.0
4   10.0   55.53  134.0
..   ...     ...    ...
58   5.0   16.66   21.5
59  21.0   43.00    NaN
60   5.0   12.00    NaN
61  13.0   20.00    NaN
62  31.0   19.00    NaN

[63 rows x 3 columns]

In [30]:
df_3.head()

size  period  price
0  10.7   47.65  144.0
1  14.0   63.13  215.0
2   9.0   58.76  105.0
3   8.0   34.88   69.0
4  10.0   55.53  134.0